// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGJL3aiauZXkduaK1LCH0gZqdFBeaVvOE',
    appId: '1:587618649403:web:2d014b36e523f9eb60631e',
    messagingSenderId: '587618649403',
    projectId: 'nike-rerun',
    authDomain: 'nike-rerun.firebaseapp.com',
    storageBucket: 'nike-rerun.firebasestorage.app',
    measurementId: 'G-YJY76T949C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlVBp4bS_HGVEtlARIot8f5wZY4sPVbZg',
    appId: '1:587618649403:android:380639c4ef89b46160631e',
    messagingSenderId: '587618649403',
    projectId: 'nike-rerun',
    storageBucket: 'nike-rerun.firebasestorage.app',
  );
}
